### ISSUE TITLE
Checkboxes are invisible when using the Suru dark theme

### ISSUE THREAD

**Issue by Flaburgan** [ubports/ubuntu-ui-toolkit#91] opened 2020-08-29 18:15 UTC
See for example in Unity Tweak Tool:

![](https://user-images.githubusercontent.com/930064/71563725-81d57d80-2a94-11ea-8232-6ab73e3c1c30.png)

>I just checked out the code for UTTT, looks like it's using the ubuntu touch ui toolkit rather than qt quick controls 2 with suru style

From : https://github.com/ubports/qqc2-suru-style/issues/7#issuecomment-569568676

**Comment by mymike00** [comment] 2020-10-12 08:11
@cibersheep How could we solve this issue?
The problem is that `Dialog` background is [`theme.palette.normal.overlay`](https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/DialogForegroundStyle.qml#L26) (which with SuruDark is `UbuntuColors.inkstone`) and the `CheckBox` one is [`theme.palette.normal.foreground`](https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/CheckBoxStyle.qml#L32) (which with SuruDark is again `UbuntuColors.inkstone`)

With Ambiance this does not happes as the `Dialog` background is `"#FFFFFF"` and the `CheckBox` one is `UbuntuColors.porcelain`

**Comment by cibersheep** [comment] 2020-10-12 11:17
I didn't start looking into these yet.
One possible solution would be the border color of the element, so the background still looks like «empty» but improve visibility with the border.

Is it happening as well with ticks on the main layer?

**Comment by mymike00** [comment] 2020-10-12 11:31
> I didn't start looking into these yet.

Oh, sorry. I didn't want to rush you 😇 

> Is it happening as well with ticks on the main layer?

No, because the background is usually `UbuntuColors.jet`, only in `Dialog`s (and other popups too, I think) the background gets lighter. I think this was made because of contrast with the black dimmed content behind the `Dialog`..

**Comment by cibersheep** [comment] 2020-10-12 12:47
> Oh, sorry. I didn't want to rush you :innocent:

«Au contraire,» happy to address this issue.

> > Is it happening as well with ticks on the main layer?
> 
> No, because the background is usually `UbuntuColors.jet`, only in `Dialog`s (and other popups too, I think) the background gets lighter. I think this was made because of contrast with the black dimmed content behind the `Dialog`..

That's very interesting. I think that whatever we decide, it should go along with the Field/TextArea and those are behaving different as they are thought to «work» on main layer...

I like the flat look of the the TextArea. But as you can see, it behaves different in the Dialog again, as it take normal.field (I'm assuming) which should be the same for the checkboxes

![imatge](https://user-images.githubusercontent.com/6640041/95748228-f54e2180-0c99-11eb-8930-f453b2e4f80e.png)

**Comment by mymike00** [comment] 2020-10-12 13:47
>  I think that whatever we decide, it should go along with the TextField/TextArea

I agree

> I like the flat look of the the TextArea.

Me too, I prefer the flat look ver the inset one of CheckBoxes

> it take normal.field which should be the same for the checkboxes

Mmh, I must say I don't really like the TextField being darker that the background... The easiest thing would be to make darker the background of the Dialog (making it jet) and maybe put a little light grey shadow under it to make it standing a bit more onto the dimmed content behind the Dialog

Or otherwise yeah, making the checkboxes the same style as the textfield would be already better than now...

**Comment by cibersheep** [comment] 2020-10-12 21:33
> > it take normal.field which should be the same for the checkboxes
> 
> Mmh, I must say I don't really like the TextField being darker that the background... 

I agree. But `normal.field` «shouldn't» be darker but the same color as the «background» (as in Ambiance). I think is a fault of the theme that in SuruDark raised elements goes jet.

> The easiest thing would be to make darker the background of the Dialog (making it jet) and maybe put a little light grey shadow under it to make it standing a bit more onto the dimmed content behind the Dialog

Oh, that would translate Ambiance and SuruDark for the Dialog but it might give the back shadow a more presence... ¿maybe?

> Or otherwise yeah, making the checkboxes the same style as the textfield would be already better than now...

It could be the 1st step of standarization :)

**Comment by cibersheep** [comment] 2020-10-12 21:45
Mmmhmmm... a mockup looks quite good, to be  honest
![imatge](https://user-images.githubusercontent.com/6640041/95793056-05d7b980-0ce5-11eb-8aaa-b892d2265a0f.png)

**Comment by mymike00** [comment] 2020-10-13 09:18
> But `normal.field` «shouldn't» be darker but the same color as the «background» (as in Ambiance). I think is a fault of the theme that in SuruDark raised elements goes jet.

With "raised" tou mean `normal.overlay` (that is, the Dialog background), right? it goes inkstone in SuruDark, jet is `normal.background`, and `normal.field` too.

> Mmmhmmm... a mockup looks quite good, to be honest

Oh, I didn't mean that, but it looks cool indeed :star_struck: 

I meant something like this (just as an idea, I drew it quickly with gimp...), but yeah I like yours more 
![immagine](https://user-images.githubusercontent.com/28359593/95841388-9b0a9a80-0d45-11eb-8684-e356bd759324.png)

**Comment by cibersheep** [comment] 2020-10-13 10:10
> With "raised" tou mean `normal.overlay` (that is, the Dialog background), right? it goes inkstone in SuruDark, jet is `normal.background`, and `normal.field` too.

I ment the layer but I got that wrong... still get confused with the layers :D

![imatge](https://user-images.githubusercontent.com/6640041/95847424-fb510a80-0d4c-11eb-99d9-0162984ca3e3.png)

> I meant something like this (just as an idea, I drew it quickly with gimp...), but yeah I like yours more

Mmm... I think that's a bit too much

**Comment by mymike00** [comment] 2020-10-13 10:12
> Mmm... I think that's a bit too much

I didn't mean to make it that flashy, but yeah, I agree with you.

**Comment by mymike00** [comment] 2020-10-13 11:29
Do you like this? 
![immagine](https://user-images.githubusercontent.com/28359593/95854416-39532c00-0d57-11eb-8954-cc16a3775a56.png)![immagine](https://user-images.githubusercontent.com/28359593/95854436-3fe1a380-0d57-11eb-9e74-436c70243493.png)![immagine](https://user-images.githubusercontent.com/28359593/95854397-322c1e00-0d57-11eb-8167-87e803307d0d.png)

**Comment by cibersheep** [comment] 2020-10-13 12:53
Yep! I do. Maybe swaping the dark layout between Ambiance and SuruDark? So they have a bit more contrast.
I mean, I like the way it's going :)

**Comment by mymike00** [comment] 2020-10-13 13:11
> Maybe swaping the dark layout between Ambiance and SuruDark? So they have a bit more contrast.

Sure. It's like that right now because of the color of the page behind the Dialog, and the dimming rectangle being inkstone with some opacity becomes lighter with the light page behind it and darker with the dark page...

Something like `jet` with Ambiance and `inkstone` with SuruDark?

![immagine](https://user-images.githubusercontent.com/28359593/95864703-0fedcc80-0d66-11eb-84c7-f715928d5a77.png)![immagine](https://user-images.githubusercontent.com/28359593/95864712-12502680-0d66-11eb-8c7f-3d003b0b7fe5.png)

 Or, like before, pure black with Ambiance and we just make it lighter with SuruDark

![immagine](https://user-images.githubusercontent.com/28359593/95865472-06189900-0d67-11eb-8555-fa3ca5dcc0ce.png)![immagine](https://user-images.githubusercontent.com/28359593/95864712-12502680-0d66-11eb-8c7f-3d003b0b7fe5.png)

**Comment by cibersheep** [comment] 2020-10-13 20:26
> Something like `jet` with Ambiance and `inkstone` with SuruDark?

I like this better. What do you think?

**Comment by mymike00** [comment] 2020-10-13 20:35
> I like this better. What do you think?

I like it! I'll open a new PR as I forgot to mark it as WIP while we were adjusting the colors and in the meanwhile Rodney merged it :stuck_out_tongue_winking_eye:

**Comment by cibersheep** [comment] 2020-10-13 21:01
So quick? Nice :)

**Closed as completed** 2020-10-13 21:48 UTC
